/* SourceMinder
 * Copyright 2026 Eli Bird
 *
 * This file is part of SourceMinder.
 *
 * SourceMinder is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 *  your option) any later version.
 *
 * SourceMinder is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with SourceMinder. If not, see <https://www.gnu.org/licenses/>.
 */

/* Build-time generator: embeds the .txt files under the config dirs into a
 * C source file so installed binaries carry built-in defaults and work without
 * /usr/share/sourceminder. Disk files always override the embedded copies
 * (see resolve_data_file() precedence in shared/paths.c).
 *
 * Usage: embed-config OUTPUT.c INPUT.txt...
 *
 * Each input's path is recorded exactly as given on the command line; those
 * strings are the lookup keys for embedded_config_get(), so they must match
 * the relative paths the loaders build (e.g. "c/config/keywords.txt").
 */
#include <stdio.h>
#include <stdlib.h>

/* Emit one file's bytes as a C string literal, one source line per input
 * line. Octal escapes are 3 digits so a following digit can't extend them. */
static void emit_string_literal(FILE *out, FILE *in) {
    int c;
    fprintf(out, "    \"");
    while ((c = fgetc(in)) != EOF) {
        switch (c) {
            case '\n': fprintf(out, "\\n\"\n    \""); break;
            case '\t': fprintf(out, "\\t"); break;
            case '\r': fprintf(out, "\\r"); break;
            case '"':  fprintf(out, "\\\""); break;
            case '\\': fprintf(out, "\\\\"); break;
            default:
                if (c >= 0x20 && c <= 0x7e) {
                    fputc(c, out);
                } else {
                    fprintf(out, "\\%03o", (unsigned int)c);
                }
                break;
        }
    }
    fprintf(out, "\"");
}

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: %s OUTPUT.c INPUT.txt...\n", argv[0]);
        return 1;
    }

    FILE *out = fopen(argv[1], "w");
    if (!out) {
        fprintf(stderr, "Error: cannot write %s\n", argv[1]);
        return 1;
    }

    fprintf(out,
        "/* Generated by tools/embed-config.c — DO NOT EDIT.\n"
        " * Built-in default config data; regenerated by make from the config dirs. */\n"
        "#include \"embedded_config.h\"\n"
        "#include <stddef.h>\n"
        "#include <string.h>\n"
        "\n");

    for (int i = 2; i < argc; i++) {
        FILE *in = fopen(argv[i], "rb");
        if (!in) {
            fprintf(stderr, "Error: cannot read %s\n", argv[i]);
            fclose(out);
            remove(argv[1]);
            return 1;
        }
        fprintf(out, "static const char cfg_%d[] =\n", i - 2);
        emit_string_literal(out, in);
        fprintf(out, ";\n\n");
        fclose(in);
    }

    fprintf(out,
        "static const struct {\n"
        "    const char *path;\n"
        "    const char *data;\n"
        "} entries[] = {\n");
    for (int i = 2; i < argc; i++) {
        fprintf(out, "    { \"%s\", cfg_%d },\n", argv[i], i - 2);
    }
    fprintf(out,
        "};\n"
        "\n"
        "const char *embedded_config_get(const char *relative_path) {\n"
        "    if (!relative_path) return NULL;\n"
        "    for (size_t i = 0; i < sizeof(entries) / sizeof(entries[0]); i++) {\n"
        "        if (strcmp(entries[i].path, relative_path) == 0) {\n"
        "            return entries[i].data;\n"
        "        }\n"
        "    }\n"
        "    return NULL;\n"
        "}\n");

    if (fclose(out) != 0) {
        fprintf(stderr, "Error: failed writing %s\n", argv[1]);
        remove(argv[1]);
        return 1;
    }
    return 0;
}
